from django.db import models

# Create your models here.
class Inhouse(models.Model):
    date=models.DateField()
    po=models.CharField(max_length=6)
    orderNo=models.IntegerField()
    supplier=models.CharField(max_length=25)
    lotNo=models.IntegerField()
    goods=models.CharField(max_length=20)
    numRolls=models.IntegerField()
    qty=models.IntegerField()

class order_roll(models.Model):
	orderNo=models.IntegerField()
	rollNoop=models.IntegerField()
	lotNo=models.IntegerField(default="0")
	status=models.IntegerField()
	
class Inspection(models.Model):
	orderNo=models.IntegerField()
	supplier=models.CharField(max_length=25)
	fabrictype=models.CharField(max_length=25)    
	fabricshade=models.CharField(max_length=25)
	acceptancePointYard=models.IntegerField()
	acceptancePointMeter=models.IntegerField()
	lotNo=models.IntegerField()
	totalRolls=models.IntegerField()
	inspectionPer=models.FloatField()
	rollNo=models.IntegerField()
	fabricWidth=models.FloatField()
	unit1=models.CharField(max_length=25)
	srl=models.FloatField()
	unit2=models.CharField(max_length=25)
	arl=models.FloatField()
	unit3=models.CharField(max_length=25)
	deviation=models.FloatField()
	unit4=models.CharField(max_length=25)
	nod=models.CharField(max_length=25)
	lp=models.IntegerField()
	hp=models.IntegerField()
	tp=models.IntegerField()
	pphuny=models.FloatField()
	pphunm=models.FloatField()
	shadeVar=models.CharField(max_length=25)
	shadeGrade=models.CharField(max_length=25)
	CSV=models.CharField(max_length=25)
	shrinkage=models.FloatField()
	result=models.CharField(max_length=25)
	desType=models.CharField(max_length=25)
	repeat_size=models.FloatField()
	wv1=models.FloatField()
	wv2=models.FloatField()
	wv3=models.FloatField()
	fgrade=models.CharField(max_length=25)
	test=models.CharField(max_length=25, default="Don't accept")

	
class ApproveInventory(models.Model):
	orderNo=models.IntegerField()
	supplier=models.CharField(max_length=25)
	grn=models.IntegerField(default=0)
	lotNo=models.IntegerField()
	rollNo=models.IntegerField()
	fabrictype=models.CharField(max_length=25)    
	fabricshade=models.CharField(max_length=25)
	arl=models.FloatField()
	unit3=models.CharField(max_length=25)
	fabricWidth=models.FloatField()
	unit1=models.CharField(max_length=25)
	wv1=models.FloatField()
	wv2=models.FloatField()
	wv3=models.FloatField()
	fgrade=models.CharField(max_length=25)
	CSV=models.CharField(max_length=25)
	shadeGrade=models.CharField(max_length=25)
	shadeVar=models.CharField(max_length=25)
	shrinkage=models.FloatField()
	
class RejectInventory(models.Model):
	orderNo=models.IntegerField()
	supplier=models.CharField(max_length=25)
	grn=models.IntegerField(default=0)
	lotNo=models.IntegerField()
	rollNo=models.IntegerField()
	fabrictype=models.CharField(max_length=25)    
	fabricshade=models.CharField(max_length=25)
	arl=models.FloatField()
	unit3=models.CharField(max_length=25)
	fabricWidth=models.FloatField()
	unit1=models.CharField(max_length=25)
	wv1=models.FloatField()
	wv2=models.FloatField()
	wv3=models.FloatField()
	fgrade=models.CharField(max_length=25)
	CSV=models.CharField(max_length=25)
	shadeGrade=models.CharField(max_length=25)
	shadeVar=models.CharField(max_length=25)
	shrinkage=models.FloatField()
	status=models.CharField(max_length=25)