from django.db import models

# Create your models here.
class TrimInhouse(models.Model):
	date=models.DateField()
	po=models.CharField(max_length=6)
	orderNo=models.IntegerField()
	supplier=models.CharField(max_length=25)
	lotNo=models.IntegerField()
	cat=models.CharField(max_length=25)
	subcat=models.CharField(max_length=25)
	supcat=models.CharField(max_length=25)
	noc=models.IntegerField()
	tqty=models.IntegerField()
	
class order_carton(models.Model):
	orderNo=models.IntegerField()
	cartonNo=models.IntegerField(default=1)
	status=models.IntegerField(default=0)
	supplier=models.CharField(max_length=25)
	lotNo=models.IntegerField(default=1)
	cat=models.CharField(max_length=25)
	subcat=models.CharField(max_length=25)
	supcat=models.CharField(max_length=25)
	noc=models.IntegerField(default=1)
	tqty=models.IntegerField(default=1)
	aql=models.FloatField(default=1)
	insqty=models.IntegerField(default=1)
	qeachbox=models.IntegerField(default=1)
	inspcar=models.IntegerField(default=1)
	
class TrimInspection(models.Model):
	orderNo=models.IntegerField()
	cartonNo=models.IntegerField(default=1)
	supplier=models.CharField(max_length=25)
	lotNo=models.IntegerField()
	cat=models.CharField(max_length=25)
	subcat=models.CharField(max_length=25)
	supcat=models.CharField(max_length=25)
	noc=models.IntegerField()
	tqty=models.IntegerField()
	aql=models.FloatField()
	insqty=models.IntegerField()
	qeachbox=models.IntegerField()
	inspcar=models.IntegerField()
	accp=models.IntegerField()
	fqty=models.IntegerField()
	paqty=models.IntegerField()
	result=models.CharField(max_length=25)
	grade=models.CharField(max_length=25)
	status=models.IntegerField(default=0)
	
class TrimInventoryApproved(models.Model):
	orderNo=models.IntegerField()
	cartonNo=models.IntegerField(default=1)
	supplier=models.CharField(max_length=25)
	grn=models.IntegerField(default=0)
	lotNo=models.IntegerField()
	cat=models.CharField(max_length=25)
	subcat=models.CharField(max_length=25)
	supcat=models.CharField(max_length=25)
	noc=models.IntegerField()
	tqty=models.IntegerField()
	aql=models.FloatField()
	accp=models.IntegerField()
	fqty=models.IntegerField()
	paqty=models.IntegerField()
	result=models.CharField(max_length=25)
	
class TrimInventoryRejected(models.Model):
	orderNo=models.IntegerField()
	cartonNo=models.IntegerField(default=1)
	supplier=models.CharField(max_length=25)
	grn=models.IntegerField(default=0)
	lotNo=models.IntegerField()
	cat=models.CharField(max_length=25)
	subcat=models.CharField(max_length=25)
	supcat=models.CharField(max_length=25)
	noc=models.IntegerField()
	tqty=models.IntegerField()
	aql=models.FloatField()
	accp=models.IntegerField()
	fqty=models.IntegerField()
	paqty=models.IntegerField()
	result=models.CharField(max_length=25)
	status=models.CharField(max_length=25)