"""movintrendz URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import index, scan_qr, sourcing, b2b_index, gown, about, portfolio, blog, contact
from userdetail.views import login_page
from .views import label_home_page, single_blog, jeans, made_to_measure, shirt, ethnic_wear, gowns
from .views import jackets, trousers, leather, tshirts, tops, jeans_product, jeans_category, jeans_cart
from .views import jeans_checkout, jeans_contact, made_to_measure_about, made_to_measure_blog
from .views import made_to_measure_contact, made_to_measure_elements, made_to_measure_gallery
from .views import made_to_measure_main, made_to_measure_services, made_to_measure_single_blog
from .views import shirts_about, shirts_blog, shirts_blog_details, shirts_checkout, shirts_contact
from .views import shirts_main, shirts_shop, shirts_shop_details, shirts_shopping_cart, ethic_category
from .views import ethnic_cart, ethnic_checkout, ethnic_contact, ethnic_product, gowns_about, gowns_blog
from .views import gowns_contact, gowns_elements, gowns_gallery, gowns_main, gowns_services
from .views import gowns_single_blog, jackets_about, jackets_blog, jackets_blog_details, jackets_checkout
from .views import jackets_contact, jackets_main, jackets_shop, jackets_shop_details, jackets_shopping_cart
from .views import trousers_about, trousers_blog, trousers_blog_details, trousers_checkout, trousers_contact, trousers_main, trousers_shop, trousers_shop_details, trousers_shopping_cart
from .views import tshirts_cart, tshirts_category, tshirts_checkout, tshirts_contact, tshirts_product
from .views import leather_cart, leather_category, leather_checkout, leather_contact, leather_product
from .views import tops_about, tops_blog, tops_contact, tops_elements, tops_gallery, tops_main, tops_services, tops_single_blog, banner,tag_index
from enquiry.views import enquiry_sourcing
from about.views import fashion_product
# from chatbotapp import views as viewschat


urlpatterns = [
   
    
    path('rasaweb/', include('rasaweb.urls')),
    path('jet/', include(('jet.urls','jet'), namespace='jet')),
    # path('botsearch/',viewschat.botsearch , name='botsearch'),
    path('admin/', admin.site.urls),
    path('',  include("about.urls")),
    path('b2c', index, name="index"),
    # path('',include('userdetail.urls')),
    path('search', views.search, name="search"),
    path('userdetail/', include('userdetail.urls')),
    path('buisness/', include('b2b.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('customadmin/', include('customadmin.urls')),
    path('searchbrand', views.searchbrand, name="searchbrand"),    
    path('products/', include('product.urls')),
    path('api/', include('api.urls')),
    path('mydesign/', include('mydesign.urls')),
    path('loadplan/', include('loadplan.urls')),
    path('fabric/', include('fabric.urls')),
    path('operators/', include('operators.urls')),
    path('scan_qr/', scan_qr),
    # path('<str:label_tag>/',label_home_page),
    path('sew/', include('sew.urls')),
    path('cpm/', include('cpm.urls')),
    path('cut/', include('cut.urls')),
    path('trim/', include('trim.urls')),
    path('printful/', include('printful.urls')),
    path('channels/', include('channels.urls')),
    path('cal/', include('cal.urls')),
    # path('cart/', include('cart.urls')),
    path('cartnew/', include('cartnew.urls')),
    path('daily_report/', include('daily_report.urls')),
    path('checkout/', views.checkout, name="Checkout"),
    path('checkoutquick/', views.checkoutquick, name="checkoutquick"),
    path('handlerequest/', views.handlerequest, name="HandleRequest"),
    path('payment_status/', views.payment_status, name="payment_status"),
    path('confirm_order/', views.checkout, name="confirm_order"),
    path('cart/', views.cart, name="cart"),
    path('cart/<str:slug>', views.editSubscription, name='edit_subscription'),
    path('deleteSubscribeCart/', views.deleteSubscribeCart, name="deleteSubscribeCart"),
    path('update_item/', views.updateItems, name="update_item"),
    path('wallet/', include("wallet.urls")),
    path('wallet/track_order', views.track_order, name="tracker_location"),
    path('resume/', include('resume.urls')),
    path('wallet/orders/<int:order_id>', views.orderdetails),
    path('wallet/transactions/<int:order_id>', views.transactions),
    path('wishlists/', views.wishlists),
    path('set_session/', views.setSession, name='set_session'),
    path('view_session/', views.view_session, name='view_session'),
    path('del_session/', views.del_session, name='del_session'),
    path('getpdfPage/', views.getPdfPage, name='getpdfpage'),
    path('getinvoice/', views.getinvoice, name='getinvoice'),
    path('myorder/', views.myorder, name='myorder'),
    path('order_history/', views.order_history, name='order_history'),
    path('blog/', include('blogs.urls')),
    path('news/', include('news.urls')),
    path('controladmin/',include('controladmin.urls')),
    path('term',views.term,name='terms_condit'),
    path('privacy',views.privacy,name='privacy'),
   # path('b2b/', b2b_index),
    path('sourcing_up/', sourcing),
    path('gown/', gown),
    # path('about/', about),
    path('portfolio1/', portfolio),
    # path('new-portfolio/',new_portfolio),
    path('blog1/', blog),
    path('contact/', contact),
    path('single_blog/', single_blog),
    path('automation/', include('enquiry.urls')),
    path('jeans/', jeans),
    path('made-to-measure/', made_to_measure),
    path('shirt/', shirt),
    path('ethnic-wear/', ethnic_wear),
    path('gowns/', gowns),
    path('jackets/', jackets),
    path('trousers/', trousers),
    path('tshirts/', tshirts),
    path('leather/', leather),
    path('tops/', tops),
    path('jeans-product/', jeans_product),
    path('jeans-category/', jeans_category),
    path('jeans-cart/', jeans_cart),
    path('jeans-checkout/', jeans_checkout),
    path('jeans-contact/', jeans_contact),
    path('made-to-measure-about/', made_to_measure_about),
    path('made-to-measure-blog/', made_to_measure_blog),
    path('made-to-measure-contact/', made_to_measure_contact),
    path('made-to-measure-elements/', made_to_measure_elements),
    path('made-to-measure-gallery/', made_to_measure_gallery),
    path('made-to-measure-main/', made_to_measure_main),
    path('made-to-measure-services/', made_to_measure_services),
    path('made-to-measure-single-blog/', made_to_measure_single_blog),
    path('shirt-about/', shirts_about),
    path('shirt-blog-details/', shirts_blog_details),
    path('shirt-blog/', shirts_blog),
    path('shirt-checkout/', shirts_checkout),
    path('shirt-contact/', shirts_contact),
    path('shirt-main/', shirts_main),
    path('shirt-shop/', shirts_shop),
    path('shirt-shop-details/', shirts_shop_details),
    path('shirt-shopping-cart/', shirts_shopping_cart),
    path('ethnic-wear-category/', ethic_category),
    path('ethnic-wear-cart/', ethnic_cart),
    path('ethnic-wear-checkout/', ethnic_checkout),
    path('ethnic-wear-contact/', ethnic_contact),
    path('ethnic-wear-product/', ethnic_product),
    path('gowns-about/', gowns_about),
    path('gowns-blog/', gowns_blog),
    path('gowns-contact/', gowns_contact),
    path('gowns-elements/', gowns_elements),
    path('gowns-gallery/', gowns_gallery),
    path('gowns-main/', gowns_main),
    path('gowns-services/', gowns_services),
    path('gowns-single-blog/', gowns_single_blog),
    path('jackets-about/', jackets_about),
    path('jackets-blog/', jackets_blog),
    path('jackets-blog-details/', jackets_blog_details),
    path('jackets-checkout/', jackets_checkout),
    path('jackets-contact/', jackets_contact),
    path('jackets-main/', jackets_main),
    path('jackets-shop/', jackets_shop),
    path('jackets-shop-details/', jackets_shop_details),
    path('jackets-shopping-cart/', jackets_shopping_cart),
    path('trousers-about/', trousers_about),
    path('trousers-blog/', trousers_blog),
    path('trousers-blog-details/', trousers_blog_details),
    path('trousers-checkout/', trousers_checkout),
    path('trousers-contact/', trousers_contact),
    path('trousers-main/', trousers_main),
    path('trousers-shop/', trousers_shop),
    path('trousers-shop-details/', trousers_shop_details),
    path('trousers-shopping-cart/', trousers_shopping_cart),
    path('tshirts-cart/', tshirts_cart),
    path('tshirts-category/', tshirts_category),
    path('tshirts-checkout/', tshirts_checkout),
    path('tshirts-contact/', tshirts_contact),
    path('leather-cart/', leather_cart),
    path('leather-category/', leather_category),
    path('leather-checkout/', leather_checkout),
    path('leather-contact/', leather_contact),
    path('leather-product/', leather_product),
    path('tshirts-product/', tshirts_product),
    path('tops/', tops),
    path('tops-about/', tops_about),
    path('tops-blog/', tops_blog),
    path('tops-contact/', tops_contact),
    path('tops-elements/', tops_elements),
    path('tops-gallery/', tops_gallery),
    path('tops-main/', tops_main),
    path('tops-services/', tops_services),
    path('tops-single-blog/', tops_single_blog),    
    # path('about-jgi/', include("about.urls")),
    path('kudugudu/', include("kudugudu.urls")),
    path('academy/', include("academy.urls")),
    path('cabs/', include("cabs.urls")),
    path('connect/', include("just_connect.urls")),
    path('phinix/', include("phinix.urls")),    
    path('personalise/', tops, name="personalise"),
    path('customise/', trousers, name="customise"),
    path('visualise-3D/', tshirts, name="visualise"),
    path('consulting/', fashion_product, name="consulting"),
    path('sourcing/', enquiry_sourcing, name="sourcing"),
    path('2D/', gown, name="2D"),
    path('3D/', jackets, name="3D"),
    path('designing/', jeans, name="designing"),
    path('sampling/', leather, name="sampling"),
    path('placeorder/', made_to_measure, name="placeorder"),
    path('measurement-chart/', shirt, name="measurement_chart"),
    path('size&fit/', tops, name="size&fit"),
    path('techpack/', trousers, name="techpack"),
    path('consumption/', tshirts, name="consumption"),
    path('lead-time/', ethnic_wear, name="lead_time"),
    path('merchandising/', gowns, name="merchandising"),
    path('t&a', jackets, name="t&a"),
    path('capacity-planning/', jeans, name="capacity_planning"),
    path('bom/', leather, name="bom"),
    path('costing/', made_to_measure, name="costing"),
    path('roll-planning/', tops, name="roll_planning"),
    path('spreading/', trousers, name="spreading"),
    path('CAD/', tshirts, name="CAD"),
    path('cut-order-plan/', ethnic_wear, name="cut_order_plan"),
    path('lay-lot-plan/', gowns, name="lay_lot_plan"),
    path('finishing/', jackets, name="finishing"),
    path('warehouse/', jeans, name="warehouse"),
    path('logistic/', leather, name="logistic"),
    path('material-tracking/', made_to_measure, name="material_tracking"),
    path('layout/', tops, name="layout"),
    path('SMED/', trousers, name="smed"),
    path('line-balancing/', tshirts, name="line_balancing"),
    path('visual-management/', ethnic_wear, name="visual_management"),
    path('order-report/', gowns, name="order_report"),
    path('lean/', jackets, name="lean"),
    path('automate/', jeans, name="automate"),
    path('factory-setup/', made_to_measure, name="factory_setup"),
    path('graphics/', trousers, name="graphics"),
    path('UI/', tshirts, name="ui"),
    path('UX/', ethnic_wear, name="ux"),
    path('visual-merchandising/', gowns, name="visual_merchandising"),
    path('fashion-forecasting/', jackets, name="fashion_forecasting"),
    path('photography/', jeans, name="photography"),
    path('inolio/', made_to_measure, name="inolio"),
    path('stylothon/', tops, name="stylothon"),
    path('miha/', trousers, name="miha"),
    path('justio/', tshirts, name="justio"),
    path('spyturtle/', ethnic_wear, name="spyturtle"),
    path('designer/', gowns, name="designer"),
    path('software/', include("software.urls")),    
    path('landscape/', jackets, name="landscape"),
    path('urban-planning/', jeans, name="urban-planning"),
    path('styling/', made_to_measure, name="styling"),
    path('rainush/', tops, name="rainush"),
    path('minaar/', trousers, name="minaar"),
    path('product-development/', tshirts, name="product-development"),
    path('sourcing/',include("quick_costing.urls")),
    path('branding/', include("branding.urls")),
    path('space/', include("archplan.urls")),
    path('careers/', include("career.urls")),
    path('diet_plan/', include("diet_plan.urls")),
    path('capacity/',include('capacityrevenue.urls')),
    path('inputform/', include('jgi.urls')),
    path('logo/', banner, name="logo"),
    path('<str:base_name>/', tag_index,name='filterproducts'),
  #  path('actionUrl', fabric_index),
  #   path('quick_costing/',include("quick_costing.urls")), change to sourcing
    path('rent/',include("rent.urls")),
    path('newrentapp/',include("newrentapp.urls")),
    path('sbs/',include("sbs.urls")),
    path('letsgo/',include("letsgo.urls")),
    path('studio/',include("studio.urls")),
    # path('', include("walior.urls")),
    # path('bodyscan/', include('main.urls')),


#ignite india   
path('igniteindia/',include("clone.urls")),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
