from django.db import models

# Create your models here.

class Requisition(models.Model):
    traveltype = models.CharField(max_length = 150)
    purpose = models.CharField(max_length = 50)
    purposedescrip = models.CharField(max_length = 150)
    journeytype = models.CharField(max_length = 30)
    mode1 = models.CharField(max_length = 100)
    placefrom1 = models.CharField(max_length = 100)
    placeto1 = models.CharField(max_length = 100)
    traveldate1 = models.DateField()
    etd1 = models.CharField(max_length = 100)
    class1 = models.CharField(max_length = 100)
    airtrain1 = models.CharField(max_length = 100)
    bookingtype1 = models.CharField(max_length = 100)
    mode2 = models.CharField(max_length = 100)
    placefrom2 = models.CharField(max_length = 100)
    placeto2 = models.CharField(max_length = 100)
    traveldate2 = models.DateField()
    etd2 = models.CharField(max_length = 100)
    class2 = models.CharField(max_length = 100)
    airtrain2 = models.CharField(max_length = 100)
    bookingtype2 = models.CharField(max_length = 100)
    nationality = models.CharField(max_length = 100)
    passportno = models.IntegerField()
    placeofissue = models.CharField(max_length = 100)
    dateofissue = models.DateField()
    dateofexpiry = models.DateField()
    dateofbirth = models.DateField()
    advancedreq = models.CharField(max_length = 10)
    travelinsurance = models.CharField(max_length = 10)
    visa = models.CharField(max_length = 10)
    simcard = models.CharField(max_length = 10)

class Vouchers(models.Model):
    fromdate = models.DateField()
    todate = models.DateField()
    days = models.IntegerField()
    nights = models.IntegerField()
    accomodation = models.CharField(max_length = 30)
    hotelname = models.CharField(max_length = 50)
    city = models.CharField(max_length = 30)
    roomrent = models.IntegerField()
    taxes = models.IntegerField()
    allcost = models.IntegerField()
    excesscost = models.IntegerField()
    justification = models.CharField(max_length = 50)
    companygst = models.IntegerField()
    hotelgst = models.IntegerField()
    hotelstate = models.CharField(max_length = 50)
    grandtotal = models.IntegerField()

class Wage(models.Model):
    department = models.CharField(max_length = 30)
    line_number = models.CharField(max_length = 30)
    month = models.CharField(max_length=30, null = True)
    employee = models.IntegerField()
    amount = models.IntegerField()


class Minute(models.Model):
    date = models.DateField()
    line = models.CharField(max_length = 30)
    minutes = models.IntegerField()

class Direct_Wage(models.Model):
    Month = models.CharField(max_length=30)
    Wages = models.IntegerField()
    Total = models.IntegerField()

class Factory_Overhead(models.Model):
    month                   = models.CharField(max_length=30)
    bonus_incentives_others = models.IntegerField()
    carrying                = models.IntegerField(null=True)
    earn_leave_allowances   = models.IntegerField()
    electricity_bill        = models.IntegerField()
    epf_expenses            = models.IntegerField()
    factory_rent            = models.IntegerField()
    factory_supply          = models.IntegerField()
    food_expenses           = models.IntegerField()
    generator_fuel          = models.IntegerField()
    import_charges          = models.IntegerField()
    import_freight_charges  = models.IntegerField()
    insurance_premium       = models.IntegerField()
    labour_charge           = models.IntegerField()
    land_rent               = models.IntegerField()
    medical_expenses        = models.IntegerField()
    misc_expenses           = models.IntegerField()
    repair_nd_main          = models.IntegerField()
    small_tools_spares      = models.IntegerField()
    transport               = models.IntegerField()
    travel_conveyance       = models.IntegerField()
    water_bill              = models.IntegerField()
    welfare_fund            = models.IntegerField()
    total                   = models.IntegerField()

class Administrative_Expenses(models.Model):
    Month                   = models.CharField(max_length=30)
    Bonus_incentives_others = models.IntegerField()
    Compliance_expenses     = models.IntegerField()
    Earn_leave_allowance    = models.IntegerField()
    Fuel_nd_Lubricant       = models.IntegerField()
    House_expenses          = models.IntegerField()
    House_rent              = models.IntegerField()
    Medical_expenses        = models.IntegerField()
    Miscellaneous           = models.IntegerField()
    Office_supplies         = models.IntegerField()
    Postage_courier         = models.IntegerField()
    Professional_fees       = models.IntegerField()
    Repair_nd_Maintain      = models.IntegerField()
    Salary_nd_Remuneration  = models.IntegerField()
    Security_charges        = models.IntegerField()
    Stationary              = models.IntegerField()
    Subscription_fee        = models.IntegerField()
    Telephone_nd_Internet   = models.IntegerField()
    Transport               = models.IntegerField()
    Travel                  = models.IntegerField()
    Visa_fee                = models.IntegerField()
    Total                   = models.IntegerField()

class Commercial_Expenses(models.Model):
    Month               = models.CharField(max_length=30)
    Commercial_expenses = models.IntegerField()
    Export_charges      = models.IntegerField()
    Sample_expenses     = models.IntegerField()
    Total               = models.IntegerField()

class Financial_Expenses(models.Model):
    Month               = models.CharField(max_length=30)
    Bank_charges        = models.IntegerField()
    Export_bank_charges = models.IntegerField()
    LC_related_charges  = models.IntegerField()
    Total               = models.IntegerField()

class Mon_Minute(models.Model):
    month = models.CharField(max_length=30)
    line = models.CharField(max_length=30)
    minutes = models.IntegerField()
