from django.urls import path, include
from . import views
from .views import (index, get_profiles, member_profile, my_profile, my_profile_edit, member_profile, follow, events, news_detail_view, upcomming_events_view, news_list_view,
                    event_detail_view, events_manage, get_profiles, create_event_view, update_event, news_update_view, news_create_view)
from .views import *

urlpatterns = [
    path('', index, name="just-connect"),
    path('get_profiles/', get_profiles, name='get_profiles'),
    path('member-profile/', member_profile, name="member_profile"),
    path('my-profile/', my_profile, name="my_profile"),
    path('my-profile-edit/', my_profile_edit, name="my_profile_edit"),
    path('member-profile/', member_profile, name="member_profile"),
    path('follow/', follow, name="follow"),
    path('member-profile/', member_profile, name="visit_profile"),
    path('events/', events, name="connect-event"),
    path('news/', news_list_view, name="connect-news-list"),
    path('news/create', news_create_view, name="connect-news-create"),
    path('news/update/<slug:slug>', news_update_view, name="connect-news-update"),
    path('news/<slug:slug>', news_detail_view, name="connect-news-detail"),
    path('events/manage', events_manage, name="connect-event-manage"),
    path('events/add', create_event_view, name="connect-event-add"),
    path('events/update/<slug:slug>', update_event, name="connect-event-update"),
    path('events/<slug:slug>', event_detail_view, name="connect-event-detail"),
    path('events/upcoming/', upcomming_events_view, name="connect-upcoming-list"),
    path('post_like', post_like, name="likePost"),
    path('post_share', share_post, name="sharePost"),
    path('post_comment', postComment, name="comments"),
    path('add_post', createPost, name="addpost"),
    path('post_poll',submit_poll ,name="PostPoll"),
    path('savedraft', Draft, name="draftpost"),
    path('draft', draftIndex, name="showDraft"),
    path('postdraft/<int:pk>',postDraft,name="post-draft"),
    path('bookmark', BookmarkIndex, name="bookmarks"),
    path('c_products', cProductIndex, name="cproducts"),
    path('c_product_order', cProductOrdersIndex, name="cproductsorders"),
    path('c_product_order/booked', Booking, name="bookProduct"),
    path('c_proudct_order/order', order_product, name="OrderProduct"),    
    path('bookmark/<int:pk>', addBookmark, name="addbookmark"),
    path('post/<int:pk>',PostDetailView,name="postdetail"),
    path('post/<int:pk>/delete',deletePost,name="deletepost"),
    path('post/<int:pk>/edit',PostEditView,name="editpost"),
    path('page/create', page_create_view, name="connect-page-create"),
    path('page/<slug:slug>', page_detail_view, name="connect-page-detail"),
    path('page/edit/<slug:slug>', page_edit_view, name="connect-page-edit"),
    path('portfolio/create_project/', create_project, name="create_project"),
    path('project/<slug:slug>/', project_view, name="ProjectView"),
    path('project/delete_project/<slug:slug>/', project_delete, name = "DeleteProject"),
    path('project/edit_project/<slug:slug>/', project_edit, name = "EditProject"),
    path('project/discover', discoverProject, name = "DiscoverProject"),
    path('project/', project_feed , name="ProjectFeed"),

]
