from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('',views.dashboard,name='dashboard'),
    path('admin',views.admins_panel,name='admins_panel'),
    path('delivery',views.delivery_panel,name='deliverypanel'),
    path('companyorder',views.company_OrderListView.as_view(),name='companyorder'),
    path('products',views.vendor_product_list,name='product'),
    # path('product',views.productListView.as_view(),name='product'),
    # path('order',views.OrdersListView.as_view(),name='order'),
    path('order',views.vendor_order_list,name='order'),
    path('rentorders',views.vendor_rent_order_list,name='rentorders'),
    path('pickup',views.vendor_pickup_list,name='pickup'),
    path('allorder',views.admins_allorder,name='allorder'),
    path('assign/<int:some_id>',views.assign_deliveryboy,name='assign_deliveryboy'),
    path('userdetail',views.detailListView.as_view(),name='userdetail'),
    path('product/<slug:slug>/update',views.productUpdateView,name='productupdate'),
    # path('product/<slug:slug>/update',views.newProductUpdateView ,name='productupdate'),
    path('product/<slug:slug>/product_quick_edit',views.productQuickeditView.as_view(),name='productedit'),
    path('product/<slug:slug>/delete',views.productDeleteView.as_view(),name='productdelete'),
    path('order/<int:pk>/update',views.orderUpdateView.as_view(),name='orderupdate'),
    path('order/<int:pk>/delete',views.orderDeleteView.as_view(),name='orderdelete'),
    path('userdetail/<int:pk>/update',views.userdetailUpdateView.as_view(),name='userdetailupdate'),
    path('userdetail/<int:pk>/delete',views.userdetailDeleteView.as_view(),name='userdetaildelete'),
    path('companyorder/<int:pk>/update',views.companyorderUpdateView.as_view(),name='companyorderupdate'),
    path('companyorder/<int:pk>/delete',views.companyorderDeleteView.as_view(),name='companyorderdelete'),
    path('vendor',views.vendorListView.as_view(),name='vendor'),
    path('vendor/<int:pk>',views.vendorDetailView,name='vendor'),
    # path('vendor/<int:pk>/orders',views.vendorOrderView.as_view(),name='vendororder'),
    path('vendor/<int:pk>/<int:pk1>/orders/<slug:slug>/delivery',views.deliverycreate,name='delivery'),
    path('vendor/<int:pk>/<int:pk1>/orders/edit',views.editorder,name='editorder'),
    # path('vendor/<int:pk>/orders/delete',views.orderitemDeleteView.as_view(),name='deleteorderitem'),
    path('vendor/<int:pk>/orders/deliverydetails',views.logisticsvendorListView.as_view(),name='logisticsvendorListView'),
    path('deliveryboy',views.deliveryboylist,name='deliveryboylist'),
    path('delivery/<int:pk>',views.deliveryadmin,name='deliveryadmin'),
    path('delivery/<int:pk>/picked/<int:pk1>',views.pickstatus,name='pickstatus'),
    path('delivery/<int:pk>/delivered/<int:pk1>',views.deliverstatus,name='deliverstatus'),
    path('accept',views.accept,name='accept'),
    path('reject',views.reject,name='reject'),
    path('rejectedorder',views.rejectedorder,name='rejectedorder'),
    path('assign/<int:pk>',views.assign,name='assign'),
    path('deliveryaccept',views.deliveryaccept,name='deliveryaccept'),
    path('deliveryreject',views.deliveryreject,name='deliveryreject'),
    path('rejecteddelivery',views.rejecteddelivery,name='rejecteddelivery'),
    path('deliveryassign/<int:pk>',views.deliveryassign,name='deliveryassign'),
    path('deliveryacceptbyboy/<int:pk>',views.deliveryacceptbyboy,name='deliveryacceptbyboy'),
]
